### PR TITLE
Fix permission when use multi sentences with use space

### LINKED ISSUE #1109: The permissions bug when multi sentences with use sentence.
Screen Shot 2021-06-04 at 11 21 55

### PR DESCRIPTION
**Pull request by laura-ding**
close #1109

### CODE REVIEW

File: src/validator/UseValidator.cpp [hunk 1]
```diff
@@ -42,7 +45,10 @@ Status UseValidator::validateImpl() {
 
 Status UseValidator::toPlan() {
     // The input will be set by father validator later.
-    auto switchSpace = SwitchSpace::make(qctx_, nullptr, *spaceName_);
+    auto switchSpace = SwitchSpace::make(qctx_,
+                                         nullptr,
+                                         *spaceName_,
+                                         qctx_->rctx()->session()->space());
```
Comment (yixinglu) [inline src/validator/UseValidator.cpp:51]: Do we still need to save old space in this plan node ?

**Review by yixinglu — APPROVED** [review]

**Review by bright-starry-sky — APPROVED** [review]
