### PR TITLE
Fix filter bug

### LINKED ISSUE #445: filter bug
The following nGQL statement will report an error:
```
GO FROM "Russell Westbrook" OVER * WHERE $$.player.age > 20;
Internal Error: Wrong type result, should be NULL type or BOOL type
```
Expected: Returns the endpoint of all edges starting from "Russell Westbrook" and satisfies the endpoint filter condition.

### PR DESCRIPTION
**Pull request by czpmango**
Fixes #445 

Depends on vesoft-inc/nebula-common#329

### CODE REVIEW

File: src/executor/query/FilterExecutor.cpp [hunk 1]
```diff
@@ -33,11 +33,11 @@ folly::Future<Status> FilterExecutor::execute() {
     auto condition = filter->condition();
     while (iter->valid()) {
         auto val = condition->eval(ctx(iter.get()));
-        if (!val.isBool() && !val.isNull()) {
+        if (!val.empty() && !val.isBool() && !val.isNull()) {
             return Status::Error("Internal Error: Wrong type result, "
                                  "should be NULL type or BOOL type");
```
Comment (jievince) [inline src/executor/query/FilterExecutor.cpp:38]: Forget to modify the error message

Comment (czpmango) [reply src/executor/query/FilterExecutor.cpp:38]: Got it, thx.

**Review by jievince — DISMISSED** [review]

**Review by CPWstatic — DISMISSED** [review]

**Review by yixinglu — APPROVED** [review]

**Review by nevermore3 — APPROVED** [review]

**Review by CPWstatic — APPROVED** [review]

**Review by yixinglu — APPROVED** [review]
